### PR TITLE
Use the scroll view's contentInset in TUITableView

### PR DESCRIPTION
**Pull request by joshaber**

### CODE REVIEW

**Comment by saidmarouf** [comment]
This is causing an issue when resizing the tableview. 
To reproduce in the Example project:
- Scroll tableview to bottom.
- Resize window.
- Scroll back to top.

Result:
- tableview cells scroll beyond the appropriate offset.

**Comment by joshaber** [comment]
I can't seem to repro that. Do you have any local changes?

**Comment by saidmarouf** [comment]
I tested this on the latest commit with no local changes. I am on Snow Leopard.. could that be a factor?

**Comment by saidmarouf** [comment]
Actually there is no need to scroll the tableview. Simply resizing it causes the issue. I have a screen grap of this: http://cl.ly/0X3S3h40211U191m390t

**Comment by joshaber** [comment]
I'm traveling so I haven't been able to test this on a 10.6 machine.

I assume you've tried reverting this change to make sure it's the real cause of the problem? It seems like a pretty simple change.

**Comment by lorenbrichter** [comment]
This change isn't the cause, haven't had time to track down which one did it.

**Comment by joshaber** [comment]
Once I'm back home with access to a 10.6 machine, I can take a look at this. I assume I introduced it somewhere along the line.

**Comment by saidmarouf** [comment]
Setting the initial offset to zero solves the issue on my side (10.6). This was the case in earlier commits. Also _contentHeight should be set to offset at line 268.

**Comment by joshaber** [comment]
I'd be interested in seeing a diff of the changes to fix it.

**Pull request merged**
