### PR TITLE
ARC Migration

### PR DESCRIPTION
**Pull request by jspahrsummers**
High-level changes:
- Migrated framework project and sample project to ARC.
- Moved build settings identical across targets up to the project level.
- Enabled static analysis with every build.
- Enabled link-time optimization in release builds.

Specific source-level changes (besides trivial ARC migration fixes):
- Removed overridden release/retain logic from `TUIFastIndexPath` – necessary for ARC.
- Renamed `TUICGImageFromBitmapContext()` to `TUICreateCGImageFromBitmapContext()`, changing its memory management semantics in the process – necessary for ARC.
- Refactored `-[TUIImage innerShadowWithOffset:radius:color:backgroundColor:]` and `-[TUIImage embossMaskWithOffset:]` to not assign to `self` – necessary for ARC.
- Refactored how `TUIView` handles subviews, keeping them in an explicit array instead of relying on finding them as layer delegates. Not _strictly_ necessary for ARC, but this made the code a lot cleaner (and hopefully clearer) than otherwise.
- In `TUIGraphicsBeginImageContextWithOptions()` and `TUIGraphicsEndImageContext()`, expect `NSGraphicsContext` to retain the context, balancing our retain count for the static analyzer. If this is a faulty assumption, this change can be reverted.
- Removed deprecated `TUIFont` methods.

This was not exhaustively tested by any means (I don't have an existing project using TwUI), but both included projects build without issue, and the sample project runs without issue on 10.7.

### CODE REVIEW

**Comment by lorenbrichter** [comment]
This is awesome, thanks (sorry I missed it until now). Not sure if everyone is ready to make the jump, but I'd love to merge this in soon.

**Comment by mrjjwright** [comment]
I am ready.  All my other code is ARC now and getting tired of excluding TwUIKit every time from ARC compilation.

**Comment by erndev** [comment]
Same here. I create all new projects with ARC, and in github it also seems the trend. Since twui is quite recent, it's likely to be used in new projects, and not added to old ones, so i guess it's a natural step to move to ARC.. 
My only concern was backwards compatibility (10.6), but it seems it's been taken care of by using __unsafe_unretained instead of weak.

just my 2¢...

**Comment by joshaber** [comment]
:+1:

**Comment by Machx** [comment]
I'd like to add my vote for merging this in

**Pull request merged**
