### PR TITLE
Various scroll view improvements

### PR DESCRIPTION
**Pull request by bww**
This includes a variety of scrolling updates.

Horizontal scrolling now suports pull/bounce/throw.  It just mirrors the vertical approach to these things.  It works fine for scrolling on both axises at once, too.

I've also added a few options to `TUIScrollView` to provide more control over bouncing:

``` objc
@property (nonatomic) BOOL bounces;
@property (nonatomic) BOOL alwaysBounceVertical;
@property (nonatomic) BOOL alwaysBounceHorizontal;
```

The new `bounces` property just enables or disables bouncing on both axises (same as UIKit).  It's just an interface to the already existing `_scrollViewFlags.bounceEnabled` flag.  It defaults to the same value as it previously did, but the user now has the option to change it.

The new `alwaysBounceVertical` and `alwaysBounceHorizontal` properties do the same thing as they do in UIKit: control whether scrolling still pulls/bounces when the content fits entirely within the scroll view on a particular axis.  Both default to `FALSE` as they do in UIKit (_which differs from the previous behavior_).

### CODE REVIEW

**Comment by lorenbrichter** [comment]
This is awesome.  Could you include a small example view (as part of the example project?) that shows this off, and we can use it to keep the feature from regressing.

**Comment by bww** [comment]
I just added a scroll view example to the example project (Window → Scroll View Example).  I also fixed a couple issues I noticed with horizontal throw/bounce.

**Comment by lorenbrichter** [comment]
Awesome.  Playing with it now, here's where it's breaking down for me:

I have a trackpad, say I two-finger scroll and pull vertically (so I'm in the "pull" state), then start moving my fingers left+right to scroll horizontally while I'm in the vertical pull state.... what seems to happen is that my horizontal scrolls are amplified so it feels really slippery.  I think this is all a matter of only having a single _pull.pulling flag, rather than a .pullingX and .pullingY so each axis is calculated independently.

There may be a problem down the road with only having a single _throw.throwing and _bounce.bouncing state as well.

**Comment by bww** [comment]
Alright, I'm getting that too.  Let me see what I can do about it.

**Comment by bww** [comment]
This is feeling a lot better to me on a trackpad now.  I split x/y-axis pulling flags and cleaned some things up accordingly.  Having single throw/bounce flags doesn't seem to be causing any obvious problems at the moment.

**Comment by lorenbrichter** [comment]
That feels fantastic.  Definitely good enough that we can tweak if needed from master.  Merging.

**Pull request merged**
